# Site settings
title: MNNIT Project Blog
email: teamdevops.mnnit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Team DevOps is a project development team of MNNIT Allahabad. We develop softwares for our clients
  according to their needs and requirements. We like to take challenging problems and provide solution
  to them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://teamdevops.github.io" # the base hostname & protocol for your site
twitter_username: TeamDevOps5
github_username:  teamdevops

# Build settings
markdown: kramdown
highlighter: pygments